version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: chatapp-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: chatapp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chatapp_audit
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mongo_data:
  mysql_data:
